movies/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
]

movies/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

movies/movies/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Movie
from .forms import MovieForm

def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    return render(request, 'movies/create.html')

def new(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Movie(title=title, content=content)
    article.save()
    return redirect('movies:index')

movies/movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
  <h1>Create</h1>
  <form action="{% url "movies:new" %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">Title : </label>
      <input type="text" id="title" name="title">
    </div>
    <div>
      <label for="content">Description : </label>
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <input type="submit">
  </form>
  <hr>
{% endblock content %}

movies/movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}
<h1>INDEX PAGE</h1>
<div class="row">
{% for movie in movies %}
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ movie.title }}</h5>
          <p class="card-text">{{ movie.content }}</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
{% endfor %}
  </div>
{% endblock content %}